"""add post location

Revision ID: e088ff233f65
Revises: 6efd18cec87c
Create Date: 2022-07-12 01:38:25.199966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e088ff233f65'
down_revision = '6efd18cec87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('location', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'location')
    # ### end Alembic commands ###
